token: 'ODQ2ODI4Mjg5OTQ3MDc0NTkx.YK1MTQ.LLjNpVyT5rvqqtSb8gkIxRsg5AA'
client-id: 'XvvMwd88D8Mu7GNRQkDw3U7f9VTvkGXF'
access-token: '0boybpeop4erppu61s0exw'
command-prefix: '.'
channels:
  leaderboard: 847183052186583070
  spell-point: 848477328400449557
  # bot-commands: 123